### ISSUE TITLE
Implement unit-testing

### ISSUE THREAD

**Issue by MrPresent** [MrPresent/djs-discord-bot#4]
### Description
unit-testing should be implemented to ensure code-quality

### Tasks
- [ ] fully implement unit-testing
  - [ ] restructure code to be easy to test
  - [ ] create and write testfiles
  - [ ] achieve near to full test-coverage
